#!/usr/bin/env bash
set -euo pipefail

NETWORK="${LOGARYS_DOCKER_NETWORK:-logarys}"
MONGO_URL="${LOGARYS_MONGO_URL:-mongodb://mongodb:27017}"
MONGO_DB="${LOGARYS_MONGO_DB:-logarys}"
PIPELINE_NAME="${LOGARYS_TEST_PIPELINE_NAME:-logarys-test-pipeline}"
PIPELINE_ID="${LOGARYS_TEST_PIPELINE_ID:-$PIPELINE_NAME}"
LOG_COUNT="${LOGARYS_TEST_LOG_COUNT:-100}"
LOG_COLLECTIONS="${LOGARYS_LOG_COLLECTIONS:-logs,log_entries,records}"

printf 'Seeding one pipeline and %s logs directly in MongoDB...\n' "$LOG_COUNT"
printf 'Mongo: %s/%s\n' "$MONGO_URL" "$MONGO_DB"
printf 'Collections: pipelines, %s\n' "$LOG_COLLECTIONS"

# Direct Mongo seeding is used because the current published ecosystem images do not expose
# pipeline creation or HTTP ingestion routes on the tested paths.
docker run --rm \
  --network "$NETWORK" \
  -e LOGARYS_MONGO_DB="$MONGO_DB" \
  -e LOGARYS_TEST_PIPELINE_NAME="$PIPELINE_NAME" \
  -e LOGARYS_TEST_PIPELINE_ID="$PIPELINE_ID" \
  -e LOGARYS_TEST_LOG_COUNT="$LOG_COUNT" \
  -e LOGARYS_LOG_COLLECTIONS="$LOG_COLLECTIONS" \
  mongo:8 \
  mongosh "$MONGO_URL/$MONGO_DB" --quiet --eval '
const dbName = process.env.LOGARYS_MONGO_DB;
const name = process.env.LOGARYS_TEST_PIPELINE_NAME;
const id = process.env.LOGARYS_TEST_PIPELINE_ID;
const count = Number.parseInt(process.env.LOGARYS_TEST_LOG_COUNT ?? "100", 10);
const collectionNames = (process.env.LOGARYS_LOG_COLLECTIONS ?? "logs")
  .split(",")
  .map((value) => value.trim())
  .filter(Boolean);

if (!Number.isInteger(count) || count <= 0) {
  throw new Error("LOGARYS_TEST_LOG_COUNT must be a positive integer");
}

const database = db.getSiblingDB(dbName);
const now = new Date();

const pipeline = {
  id,
  name,
  enabled: true,
  inputType: "http",
  description: "Test pipeline generated by scripts/load-test-data-docker.sh",
  config: {
    source: "load-test-data",
    format: "json"
  },
  updatedAt: now
};

database.pipelines.updateOne(
  { $or: [{ id }, { name }] },
  {
    $set: pipeline,
    $setOnInsert: { createdAt: now }
  },
  { upsert: true }
);

const levels = ["debug", "info", "warning", "error", "critical"];
const docs = [];

for (let index = 0; index < count; index += 1) {
  const level = levels[index % levels.length];
  const timestamp = new Date(now.getTime() - (count - index) * 1000);
  const sequence = String(index + 1).padStart(3, "0");

  docs.push({
    id: `test-log-${sequence}`,
    pipelineId: id,
    pipelineName: name,
    level,
    message: `Synthetic ${level} log #${sequence}`,
    timestamp,
    createdAt: timestamp,
    source: "load-test-data",
    raw: JSON.stringify({ event: "synthetic-log", level, sequence }),
    context: {
      index: index + 1,
      requestId: `test-${sequence}`,
      service: index % 2 === 0 ? "checkout" : "catalog",
      durationMs: 10 + index * 3,
      userAgent: "logarys-test-loader/1.0"
    }
  });
}

for (const collectionName of collectionNames) {
  const collection = database.getCollection(collectionName);
  collection.deleteMany({ pipelineId: id, source: "load-test-data" });

  if (docs.length > 0) {
    collection.insertMany(docs, { ordered: true });
    collection.createIndex({ pipelineId: 1, timestamp: -1 });
    collection.createIndex({ level: 1, timestamp: -1 });
    collection.createIndex({ message: "text", source: "text" }, { default_language: "none" });
  }

  print(`${collectionName}: ${collection.countDocuments({ pipelineId: id, source: "load-test-data" })} logs`);
}

print("pipeline:");
printjson(database.pipelines.findOne({ id }));
print("done");
'

printf '\nDone.\n'
printf 'Tip: check seeded data with:\n'
printf 'docker run --rm --network %s mongo:8 mongosh %s/%s --quiet --eval '\''db.logs.find({ pipelineId: "%s" }).limit(3).toArray()'\''\n' "$NETWORK" "$MONGO_URL" "$MONGO_DB" "$PIPELINE_ID"
